# Generated by Django 5.2.17 on 2026-08-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('CST', 'Computer Science & Technology'), ('ELECTRICAL', 'Electrical Engineering'), ('IT', 'Information Technology'), ('MECHANICAL', 'Mechanical Engineering')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('DIRECTOR', 'Director'), ('HOD', 'Head of Department'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10),
        ),
    ]
