# Generated by Django 5.2.17 on 2026-08-07 06:06

import apps.complaints.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'complaint categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_code', models.CharField(default=apps.complaints.models._generate_complaint_code, editable=False, max_length=32, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('department_or_location', models.CharField(blank=True, max_length=200)),
                ('student_urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('SPAM', 'Spam'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=15)),
                ('spam_score', models.PositiveSmallIntegerField(default=0)),
                ('spam_classification', models.CharField(choices=[('NORMAL', 'Normal'), ('REVIEW', 'Review'), ('SUSPICIOUS', 'Suspicious')], default='NORMAL', max_length=12)),
                ('is_confidential', models.BooleanField(default=False)),
                ('director_public_remark', models.TextField(blank=True)),
                ('director_internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='complaints.complaintcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_path', models.CharField(max_length=512, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('SPAM', 'Spam'), ('CLOSED', 'Closed')], max_length=15)),
                ('new_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('SPAM', 'Spam'), ('CLOSED', 'Closed')], max_length=15)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='complaints.complaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['student', 'created_at'], name='complaints__student_a585d4_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'created_at'], name='complaints__status_39c2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['category', 'created_at'], name='complaints__categor_ab3337_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['spam_classification', 'created_at'], name='complaints__spam_cl_7fcd8b_idx'),
        ),
    ]
