# Generated by Django 5.2.17 on 2026-08-09 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_forwarded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('CST', 'Computer Science & Technology'), ('ELECTRICAL', 'Electrical Engineering'), ('IT', 'Information Technology'), ('MECHANICAL', 'Mechanical Engineering')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='hod_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['assigned_department', 'created_at'], name='complaints__assigne_927817_idx'),
        ),
    ]
