# Generated by Django 5.2.17 on 2026-08-07 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplicate_score', models.PositiveSmallIntegerField(default=0)),
                ('frequency_score', models.PositiveSmallIntegerField(default=0)),
                ('low_information_score', models.PositiveSmallIntegerField(default=0)),
                ('repetition_score', models.PositiveSmallIntegerField(default=0)),
                ('prior_spam_score', models.PositiveSmallIntegerField(default=0)),
                ('similarity_score', models.PositiveSmallIntegerField(default=0)),
                ('final_score', models.PositiveSmallIntegerField(default=0)),
                ('classification', models.CharField(choices=[('NORMAL', 'Normal'), ('REVIEW', 'Review'), ('SUSPICIOUS', 'Suspicious')], default='NORMAL', max_length=12)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('rules_version', models.CharField(default='v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spam_analysis', to='complaints.complaint')),
            ],
        ),
    ]
